OurBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('books/', include('bookstore.urls')),
    path('solutions/', include('solutions.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    path('browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from main import views as main_view

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='register/index.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='register/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

school_select = (
    ("고려대학교", "고려대학교"),
    ("국민대학교", "국민대학교"),
    ("동덕여자대학교", "동덕여자대학교"),
    ("서경대학교", "서경대학교"),
    ("성신여자대학교", "성신여자대학교"),
    ("한국예술종합학교", "한국예술종합학교"),
    ("한성대학교", "한성대학교"),
)

class MyUser(AbstractUser, models.Model):
    school = models.CharField(max_length=10, choices=school_select, default="고려대학교")
    realname = models.CharField(max_length=20, blank=True, null=True)
    # mycode = models.URLField(blank=True, null=True)

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import MyUser

class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='User ID', required=True)
    email = forms.EmailField(label='E-mail', required=True)
    realname = forms.CharField(label='Name', required=True)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)
    
    class Meta:
        model = MyUser
        #fields = ('userid', 'username', 'email', 'phone', 'group')
        fields = ('username', 'email', 'school', 'realname')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password']

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm 

def register(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'register/registration_done.html', {'new_user':new_user})
    else:
        user_form = RegisterForm()

    return render(request, 'register/register.html', {'form':user_form})

accounts/templates/register/index.html
<!DOCTYPE html>
<html>

<head>
<title>OurBook</title>
<link rel="shortcut icon" href="/favicon.ico" type="/sataic/image/x-icon">
<link rel="icon" href="/static/favicon.ico" type="/static/image/x-icon">
<!-- <link rel="manifest" href="site.webmanifest"> -->
<link rel="shortcut icon" type="image/x-icon" href="/static/img/favicon.png">
<!-- Place favicon.ico in the root directory -->

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content=" Master  Login Form Widget Tab Form,Login Forms,Sign up Forms,Registration Forms,News letter Forms,Elements"/>
<link href="/static/css/mystyle.css" rel="stylesheet" type="text/css" media="all" />
<link href="//fonts.googleapis.com/css?family=Cormorant+SC:300,400,500,600,700" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
</head>

<body>
	<img src="/static/img/logo_transparent.png" width="25%">
		<div class="design-w3l">
			<div class="mail-form-agile">
				<form action="{% url 'login' %}" method="post">
					{% csrf_token %}
					<input type="text" name="username" autofocus required id="id_username">
					<input type="password" name="password" required id="id_password">
					<br/><br/>
					<input type="submit" value="login">
				</form>
				<br/>
				<a href="{% url 'register' %}" style="color:white">join us</a>
			</div>
		  <div class="clear"> </div>
		</div>
		
	</div>
</body>
</html>

accounts/templates/register/logout.html
Thank You
<br>
<a href="{% url 'login' %}">back to home</a>    

accounts/templates/register/register.html
<style>
.send-button{
background: #54C7C3;
width:100%;
font-weight: 600;
color:#fff;
padding: 8px 25px;
}
input[type=number]::-webkit-inner-spin-button, 
input[type=number]::-webkit-outer-spin-button { 
  -webkit-appearance: none; 
  margin: 0; 
}
.g-button{
color: #fff !important;
border: 1px solid #EA4335;
background: #ea4335 !important;
width:100%;
font-weight: 600;
color:#fff;
padding: 8px 25px;
}
.my-input{
box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
cursor: text;
padding: 8px 10px;
transition: border .1s linear;
}
.header-title{
margin: 5rem 0;
}
h1{
font-size: 31px;
line-height: 40px;
font-weight: 600;
color:#4c5357;
}
h2{
color: #5e8396;
font-size: 21px;
line-height: 32px;
font-weight: 400;
}
.login-or {
position: relative;
color: #aaa;
margin-top: 10px;
margin-bottom: 10px;
padding-top: 10px;
padding-bottom: 10px;
}
.span-or {
display: block;
position: absolute;
left: 50%;
top: -2px;
margin-left: -25px;
background-color: #fff;
width: 50px;
text-align: center;
}
.hr-or {
height: 1px;
margin-top: 0px !important;
margin-bottom: 0px !important;
}
@media screen and (max-width:480px){
h1{
font-size: 26px;
}
h2{
font-size: 20px;
}
}
</style>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<body>
   <div class="container">
      <div class="col-md-6 mx-auto text-center">
         <div class="header-title">
            <h1 class="wv-heading--title">
               OurBook
            </h1>
            <h2 class="wv-heading--subtitle">
              회원가입
            </h2>
         </div>
      </div>
      <div class="row">
         <div class="col-md-4 mx-auto">
            <div class="myform form ">
               <form action="" method="post"  class="user" name="login">
               {%csrf_token%}
                  <div class="form-group">
                     <input type="text" name="username"  required class="form-control my-input" id="id_username" placeholder="ID">
                  </div>

                  <div class="form-group">
                     <input type="email" name="email"  class="form-control my-input" required id="id_email" placeholder="Email">
                  </div>

                  <div class="form-group">
                     <input type="text" name="realname" required id="id_realname"  class="form-control my-input" placeholder="Name">
                  </div>

                  <div class="form-group">
                     <input type="password" name="password" required id="id_password"  class="form-control my-input" placeholder="Password">
                  </div>

                  <div class="form-group">
                     <input type="password" name="password2" required id="id_password2"  class="form-control my-input" placeholder="Repeat Password">
                  </div>


                  <div class="form-group">
                    <select class="form-control my-input" name="school" id="id_school" value="학교">
                      <option value="고려대학교" selected>고려대학교</option>
                      <option value="국민대학교">국민대학교</option>
                      <option value="동덕여자대학교">동덕여자대학교</option>
                      <option value="서경대학교">서경대학교</option>
                      <option value="성신여자대학교">성신여자대학교</option>
                      <option value="한국예술종합학교">한국예술종합학교</option>
                      <option value="한성대학교">한성대학교</option>
                    </select>
                  </div>

                  <div class="text-center ">
                     <button type="submit" class=" btn btn-block send-button tx-tfm">Create Your Free Account</button>
                  </div>

                  <div class="col-md-12 ">
                     <div class="login-or">
                        <hr class="hr-or">
                        <span class="span-or">or</span>
                     </div>
                  </div>
                  <div class="form-group">
                     <a class="btn btn-block g-button" href="#" onclick="return confirm('Social Login은 준비 중입니다 :)')">
                     <i class="fa fa-google"></i> Sign up with Google
                     </a>
                  </div>
                  <p class="small mt-3">By signing up, you are indicating that you have read and agree to the <a href="#" class="ps-hero__content__link">Terms of Use</a> and <a href="#">Privacy Policy</a>.
                  </p>
               </form>
            </div>
         </div>
      </div>
   </div>
</body>

accounts/templates/register/register_done.html
회원가입이 완료되었습니다.
<br>
<a href="/"> Back To Home </a>

accounts/templates/register/registration_done.html
회원가입이 완료되었습니다.
<br>
<a href="/"> Back To Home </a>