OurBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ckeditor_uploader import views as views_ckeditor
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('main/', include('main.urls')),
    path('books/', include('bookstore.urls')),
    path('solutions/', include('solutions.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('upload/', login_required(views_ckeditor.upload), name='ckeditor_upload'),
    path('browse/', never_cache(login_required(views_ckeditor.browse)), name='ckeditor_browse'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.books , name="books"),       # 팩 검색
    path('new/', views.new_book, name="new_book"),

    path('booklist/', views.BookList.as_view(), name="book_list"),
    path('newbook/', views.BookCreate.as_view(), name="book_create"),
    path('bookdetail/<int:pk>', views.BookDetail.as_view(), name='book_detail'),
    path('update/<int:pk>', views.BookUpdate.as_view(), name='book_change'),
    path('delete/<int:pk>', views.BookDelete.as_view(), name='book_del'),

]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
]

bookstore/models.py
from django.db import models
from accounts.models import MyUser

class UserBook(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    link = models.URLField()

    author = models.CharField(max_length=200)
    price = models.CharField(max_length=200)

    publisher = models.CharField(max_length=200)
    pub_date = models.CharField(max_length=200)
    isbn = models.CharField(max_length=200, primary_key=True)

    description = models.CharField(max_length=500)

    def __str__(self):
        return self.title


class Product(models.Model):
    
    exchange_type = (
        ("양도", "양도"),
        ("대여", "대여"),
        ("판매", "판매")
    )

    book_state = (
        ("unavailable", "unavailable"),
        ("available", "available"),
    )

    exchange_method = (
        ("일반거래", "일반거래"),
        ("중개거래", "중개거래"),
    )

    user = models.ForeignKey(MyUser, on_delete = models.CASCADE, null=True)
    
    # 사용자가 이걸 입력하는 게 좀 귀찮을 거 같은데
    book_title = models.CharField(max_length=255, blank=False, null=False, default="")
    isbn = models.CharField(max_length=255, blank=False, null=False, default="")
    
    note = models.CharField(max_length=255)     # 부가 정보
    ex_type = models.CharField(max_length=10, choices=exchange_type, default="양도")   # 대여, 양도, 판대
    state = models.CharField(max_length=10, choices=book_state, default="unavailable")   # 판매 완료
    exc_method = models.CharField(max_length=10, choices=exchange_method, default="일반거래")   # 안심거래, 일반거래 
    price = models.CharField(max_length=100, blank=True)   # 가격

    def __str__(self):
        return self.book_title

bookstore/views.py
from django.shortcuts import render, redirect
import urllib.request
import json
from django.urls import reverse_lazy

from django.utils import timezone
from django.views.generic.list import ListView # 데이터 보여주기
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView #데이터 추가
from .models import Product
from django.contrib.auth.mixins import LoginRequiredMixin

################ Book Product CRUD ############################################3

class BookList(LoginRequiredMixin, ListView):
    login_url = '/'
    redirect_field_name = '/'

    model = Product

class BookCreate(LoginRequiredMixin, CreateView):
    login_url = '/'
    redirect_field_name = '/'

    model = Product
    fields = ['book_title', 'isbn' ,'note', 'ex_type', 'exc_method']
    success_url = reverse_lazy('book_list')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)    

class BookDetail(LoginRequiredMixin, DetailView):
    login_url = '/'
    redirect_field_name = '/'
    model = Product

class BookUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/'
    redirect_field_name = '/'
    model = Product
    fields = ['book', 'note', 'ex_type', 'state', 'exc_method']
    success_url = reverse_lazy('book_list')

class BookDelete(LoginRequiredMixin, DeleteView):
    login_url = '/'
    redirect_field_name = '/'
    model = Product
    success_url = reverse_lazy('book_list')

#############################################################3

# 책 검색
def books(request):

    if request.method == 'POST':
        
        keyword = request.POST.get('book_search', '') 
        client_id = "CJNbcDFvgOnPbjtdXxA_"  # Client-Id
        client_secret = "6EdIJ7Pe2d"        # Client-Secret
        encText = urllib.parse.quote(keyword)
        
        # 우선은 3씩, 판매량 순
        url = "https://openapi.naver.com/v1/search/book?query=" + encText +"&display=10&sort=count" 
        request_content = urllib.request.Request(url)
        
        request_content.add_header("X-Naver-Client-Id", client_id)
        request_content.add_header("X-Naver-Client-Secret", client_secret)
        response = urllib.request.urlopen(request_content)
        rescode = response.getcode()
        
        if(rescode==200):
            response_body = response.read()
            # print(response_body.decode('utf-8'))

            json_rt = response_body.decode('utf-8')
            final_res = json.loads(json_rt)
            return render(request, 'books.html', {'final_res':final_res})
        
        else:
            # print("Error Code:" + rescode)
            final_res = rescode

        final_res = final_res.decode('utf-8')

        return render(request, 'books.html', {'final_res':final_res})


    # 페이지로 들어온 경우
    else:
        return render(request, 'book_list.html', {}) 

    return render(request, 'book_list.html')

def new_book(request):

    return render(request, 'save_book.html')

bookstore/templates/bookstore/product_detail.html
{% extends 'base.html' %}
{% block content %}

  <!-- bradcam_area_start -->
  <div class="bradcam_area breadcam_bg">
      <h3>전공책 공유</h3>
  </div>

 <!--================Blog Area =================-->
   <section class="blog_area single-post-area section-padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-12 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="img-fluid" src="img/blog/single_blog_1.png" alt="">
                  </div>
                  <div class="blog_details">
                     <h2>{{object.book_title}}
                     </h2>
                     <ul class="blog-info-link mt-3 mb-4">
                        <li><i class="fa fa-user"></i>게시자: {{object.user}} </li>
                        <li>ISBN : {{object.isbn}}</li>
                        
                        
                     </ul>
                <div class="blog-author">
                  <div class="media align-items-center">
                     <img src="/static/img/blog/author.png" alt="">
                     <div class="media-body">
                           <h4>{{object.ex_type}}</h4>
                        <p>{{object.exc_method}}</p>
                     </div>
                  </div>
               </div>

                  <div class="quote-wrapper">
                        <div class="quotes">
                           {{object.note}}
                        </div>
                     </div>

                  </div>
               </div>
             
               </div>
               
               <div class="comments-area">
                  <h4>05 Comments</h4>
                  <div class="comment-list">
                     <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                           <div class="thumb">
                              <img src="img/comment/comment_1.png" alt="">
                           </div>
                           <div class="desc">
                              <p class="comment">
                                 Multiply sea night grass fourth day sea lesser rule open subdue female fill which them
                                 Blessed, give fill lesser bearing multiply sea night grass fourth day sea lesser
                              </p>
                              <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <h5>
                                       <a href="#">Emilly Blunt</a>
                                    </h5>
                                    <p class="date">December 4, 2017 at 3:12 pm </p>
                                 </div>
                                 <div class="reply-btn">
                                    <a href="#" class="btn-reply text-uppercase">reply</a>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="comment-list">
                     <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                           <div class="thumb">
                              <img src="img/comment/comment_2.png" alt="">
                           </div>
                           <div class="desc">
                              <p class="comment">
                                 Multiply sea night grass fourth day sea lesser rule open subdue female fill which them
                                 Blessed, give fill lesser bearing multiply sea night grass fourth day sea lesser
                              </p>
                              <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <h5>
                                       <a href="#">Emilly Blunt</a>
                                    </h5>
                                    <p class="date">December 4, 2017 at 3:12 pm </p>
                                 </div>
                                 <div class="reply-btn">
                                    <a href="#" class="btn-reply text-uppercase">reply</a>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="comment-list">
                     <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                           <div class="thumb">
                              <img src="img/comment/comment_3.png" alt="">
                           </div>
                           <div class="desc">
                              <p class="comment">
                                 Multiply sea night grass fourth day sea lesser rule open subdue female fill which them
                                 Blessed, give fill lesser bearing multiply sea night grass fourth day sea lesser
                              </p>
                              <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <h5>
                                       <a href="#">Emilly Blunt</a>
                                    </h5>
                                    <p class="date">December 4, 2017 at 3:12 pm </p>
                                 </div>
                                 <div class="reply-btn">
                                    <a href="#" class="btn-reply text-uppercase">reply</a>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="comment-form">
                  <h4>Leave a Reply</h4>
                  <form class="form-contact comment_form" action="#" id="commentForm">
                     <div class="row">
                        <div class="col-12">
                           <div class="form-group">
                              <textarea class="form-control w-100" name="comment" id="comment" cols="30" rows="9"
                                 placeholder="Write Comment"></textarea>
                           </div>
                        </div>
                        <div class="col-sm-6">
                           <div class="form-group">
                              <input class="form-control" name="name" id="name" type="text" placeholder="Name">
                           </div>
                        </div>
                        <div class="col-sm-6">
                           <div class="form-group">
                              <input class="form-control" name="email" id="email" type="email" placeholder="Email">
                           </div>
                        </div>
                        <div class="col-12">
                           <div class="form-group">
                              <input class="form-control" name="website" id="website" type="text" placeholder="Website">
                           </div>
                        </div>
                     </div>
                     <div class="form-group">
                        <button type="submit" class="button button-contactForm btn_1 boxed-btn">Send Message</button>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!--================ Blog Area end =================-->


{% endblock %}

bookstore/templates/bookstore/product_form.html
{% extends 'base.html' %}
{% block content %}

  <!-- bradcam_area_start -->
  <div class="bradcam_area breadcam_bg">
      <h3>책 나누기</h3>
  </div>

	<!-- Start Align Area -->
	<div class="whole-wrap">
		<div class="container box_1170">		
			<div class="section-top-border">
				<div class="row">
					<div class="col-lg-8 col-md-8">
						<h3 class="mb-30">도서 기본정보 등록</h3>
    
          <form  method="post" action="#">
            {%csrf_token%}
            <div class="input-group-icon mt-10">
								<div class="icon"></div>
								<input type="text" name="book_title" placeholder="title" required id="id_book_title" maxlength="255" class="single-input">
						</div><br/>

            <div class="input-group-icon mt-10">
								<div class="icon"></div>
								<input type="text" name="isbn" placeholder="ISBN (- 뺴고 입력)" required id="id_isbn" maxlength="255" class="single-input">
						</div><br/>

            <div class="input-group-icon mt-10">
								<div class="icon"></div>
								<textarea type="text" name="note" placeholder="메세지" required id="id_note" maxlength="255" class="single-input"></textarea>
						</div><br/>

					</div>
					<div class="col-lg-3 col-md-4 mt-sm-30">
						<div class="single-element-widget">
							<h3 class="mb-30">거래 방식</h3>
							<div class="switch-wrap d-flex justify-content-between">
								<p>물품 성격</p>
								<div class="primary-switch">
                {{form.ex_type}}
								</div>
							</div>
							<div class="switch-wrap d-flex justify-content-between">
								<p>거래 방식</p>
								<div class="primary-switch">
                {{form.exc_method}}
								</div>
							</div>
						</div>

						<div class="single-element-widget mt-30">
							<h3 class="mb-30">최종 제출 </h3>
							<div>
								<p>제목, ISBN을 최종 확인셨나요?</p>
							</div>
              <input type = "submit" value ="추가" onclick="return confirm('새 책이 등록되었습니다')" class="genric-btn success">
          </form>  
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End Align Area -->
{% endblock%}

bookstore/templates/bookstore/product_list.html
{% extends 'base.html' %}
{% block content %}

  <!-- bradcam_area_start -->
  <div class="bradcam_area breadcam_bg">
      <h3>전공책 공유</h3>
  </div>
  
    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        
                        <!-- blog item -->
                      {% for product in object_list%}
                        <article class="blog_item">
                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'book_detail' product.pk%}">
                                    <h3>{{product.book_title}}</h3>
                                </a><br/><br/>
                                <p>{{product.note}}</p>
                                <ul class="blog-info-link">
                                    <li><a href="#"><i class="fa fa-user"></i> {{product.user}}</a></li>
                                    <li><a href="#">ISBN : {{product.isbn}}</a></li>
                                    <li><a href="#"><i class="fa fa-building"></i>{{product.ex_type}}</a></li>
                                    <li><a href="#"><i class="fa fa-calendar"></i>{{product.exc_method}}</a></li>
                                    <li><a href="#">State:{{product.state}}</a></li>
                                </ul>
                            </div>
                        </article>
                      {%endfor%}

                        <nav class="blog-pagination justify-content-center d-flex">
                            <ul class="pagination">
                                <li class="page-item">
                                    <a href="#" class="page-link" aria-label="Previous">
                                        <i class="ti-angle-left"></i>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a href="#" class="page-link">1</a>
                                </li>
                                <li class="page-item active">
                                    <a href="#" class="page-link">2</a>
                                </li>
                                <li class="page-item">
                                    <a href="#" class="page-link" aria-label="Next">
                                        <i class="ti-angle-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        
                        <aside class="single_sidebar_widget search_widget">
                            <a href="{%url 'book_create'%}" class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                type="submit">내 책 나누기</a>
                            </form>
                        </aside>

                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                                <li>
                                    <a href="#" class="d-flex">
                                        <p>Resaurant food</p>
                                        <p>(37)</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="d-flex">
                                        <p>Travel news</p>
                                        <p>(10)</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="d-flex">
                                        <p>Modern technology</p>
                                        <p>(03)</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="d-flex">
                                        <p>Product</p>
                                        <p>(11)</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="d-flex">
                                        <p>Inspiration</p>
                                        <p>21</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="d-flex">
                                        <p>Health Care (21)</p>
                                        <p>09</p>
                                    </a>
                                </li>
                            </ul>
                        </aside>

                        <aside class="single_sidebar_widget popular_post_widget">
                            <h3 class="widget_title">최근 올라온 책</h3>
                            
                          {% for obj in object_list %}
                            {% if forloop.counter <= 5 %}
                            <div class="media post_item">
                                <div class="media-body">
                                    <a href="single-blog.html">
                                        <a href="{% url 'book_detail' obj.pk %}"><h3>{{obj.book_title}}</h3></a>
                                    </a>
                                    <p>{{obj.ex_type}}</p>
                                </div>
                            </div>              
                            {% endif %}
                          {% endfor %}                            
          
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
{% endblock %}